query ListMessages($conversationId: ID!, $cursor: String) {
  listMessages(args: { conversationId: $conversationId, take: 40, cursor: $cursor }) {
    items {
      id
      conversationId
      content
      type
      createdAt
      clientRequestId
      sender {
        id
        username
      }
      reactions {
        emoji
        userId
        user {
          username
        }
      }
    }
    pageInfo {
      nextCursor
      hasNextPage
    }
  }
}
