mutation SendMessage($input: SendMessageInput!) {
  sendMessage(input: $input) {
    id
    conversationId
    content
    type
    createdAt
    sender {
      id
      username
    }
    reactions {
      emoji
      userId
      user {
        username
      }
    }
  }
}
